-- Add attendance_token to events table
ALTER TABLE public.events ADD COLUMN attendance_token text UNIQUE;

-- Create attendance_records table
CREATE TABLE public.attendance_records (
    id bigint generated by default as identity primary key,
    event_id bigint references public.events(id) ON DELETE CASCADE,
    attendee_name text not null,
    created_at timestamptz default now()
);

-- Enable RLS
ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users (admins) can view all attendance records
CREATE POLICY "Admins can view all attendance" ON public.attendance_records
    FOR SELECT TO authenticated USING (true);

-- Policy: Public can insert attendance records (Sign In)
-- Note: We trust the public to sign in via the UI which resolves the token.
CREATE POLICY "Public can sign in" ON public.attendance_records
    FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Policy: Admin can delete records
CREATE POLICY "Admins can delete attendance" ON public.attendance_records
    FOR DELETE TO authenticated USING (true);
